courses/urls.py
from django.urls import path

from .views import CreateStudentView
from .views import DeleteStudentView
from .views import DetailCourseView
from .views import ListCourseView
from .views import UpdateStudentView

app_name = 'courses'

urlpatterns = [
    path('create/', CreateStudentView.as_view(), name='create'),
    path('', ListCourseView.as_view(), name='list'),
    path('detail/<int:pk>/', DetailCourseView.as_view(), name='detail'),
    path('update/<int:pk>/', UpdateStudentView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteStudentView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

courses/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Course(models.Model):
    course_name = models.CharField(
        max_length=100,
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"course_name" field value less than two symbols'}
    )
    course_duration = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"course_duration" field value less than two symbols'}
    )
    course_price = models.CharField(
        max_length=20,
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"course_price" field value less than two symbols'},
    )
    course_requirements = models.TextField(
        max_length=50,
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"course_requirements" field value less than two symbols'},
        null=True,
        blank=True
    )
    group = models.OneToOneField(
        'groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='course_group'
    )
    create_datetime = models.DateTimeField(auto_now_add=True)
    update_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Course name: <{self.course_name}>; Duration: <{self.course_duration}>'

    class Meta:
        db_table = 'courses'

courses/forms.py
from django import forms

from django_filters import FilterSet

from .models import Course


class BaseCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class CreateCourseForm(BaseCourseForm):
    class Meta(BaseCourseForm.Meta):
        pass


class UpdateCourseForm(BaseCourseForm):
    class Meta(BaseCourseForm.Meta):
        pass


class CourseFilterForm(FilterSet):
    class Meta:
        model = Course
        fields = {
            'course_name': ['exact', 'icontains'],
        }

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import CourseFilterForm, CreateCourseForm, UpdateCourseForm
from .models import Course


class ListCourseView(ListView):
    model = Course
    template_name = 'courses/list.html'

    def get_queryset(self):
        courses = Course.objects.select_related('group')
        filter_form = CourseFilterForm(data=self.request.GET, queryset=courses)

        return filter_form


class DetailCourseView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/detail.html'


class CreateStudentView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CreateCourseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/create.html'


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = UpdateCourseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/update.html'


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Course
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/delete.html'

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-outline-success bth-sm mt-2" type="submit" value="Create">
                <a class="btn btn-outline-danger bth-sm mt-2" href="{% url 'courses:list' %}">Cancel</a>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}Delete course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <p>Do you really want to remove "{{ course.course_name }}"?</p>
                <input class="btn btn-outline-success bth-sm mt-2" type="submit" value="Agree">
                <a class="btn btn-outline-danger bth-sm mt-2" href="{% url 'courses:list' %}">Cancel</a>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ course.course_name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-5"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <a href="{% url 'courses:update' course.pk  %}">{{ course.course_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ course.course_duration }}</li>
                    <li class="list-group-item">{{ course.course_price }}</li>
                    <li class="list-group-item">{{ course.course_requirements }}</li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{% url 'courses:list' %}">Back to list</a>
            </div>
        </div>
        <div class="col-5"></div>
    </div>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}List of courses{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Search for a course
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <form method="get">
                                {{ object_list.form|crispy }}
                                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6"></div>
    </div>
    <h1>List of courses</h1>
    <div class="row mt-3 pt-4">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>N</th>
                <th>Name</th>
                <th>Duration</th>
                <th>Price</th>
                <th>Requirements</th>
                <th>Group</th>
                {% if user.is_authenticated %}
                    <th style="text-align: center"><i class="bi bi-pencil-fill"></i></th>
                    <th style="text-align: center"><i class="bi bi-trash3-fill"></i></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for course in object_list.qs %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {% if user.is_authenticated %}
                            <a href="{% url 'courses:detail' course.pk %}">{{ course.course_name }}</a>
                        {% else %}
                            {{ course.course_name }}
                        {% endif %}
                    </td>
                    <td>{{ course.course_duration }}</td>
                    <td>{{ course.course_price }}</td>
                    <td>
                        {% if course.course_requirements %}
                            {{ course.course_requirements }}
                        {% endif %}
                    </td>
                    <td>
                        {% if course.group %}
                            {{ course.group.group_name }} (start: {{ course.group.group_start_date }})
                        {% endif %}
                    </td>
                    {% if user.is_authenticated %}
                        <td style="text-align: center"><a class="btn btn-outline-primary bth-sm"
                                                          href="{% url 'courses:update' course.pk %}">Edit</a></td>
                        <td style="text-align: center"><a class="btn btn-outline-danger bth-sm"
                                                          href="{% url 'courses:delete' course.pk %}">Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-outline-success bth-sm mt-2" type="submit" value="Update">
                <a class="btn btn-outline-danger bth-sm mt-2" href="{% url 'courses:list' %}">Cancel</a>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}